package thepowderguy.mcflight.common.entity;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;


public class ModelBiplane extends ModelBase
{
  //fields
	ModelRenderer WingTop;
    ModelRenderer WingBottom;
    ModelRenderer FuselageLeft;
    ModelRenderer FuselageRight;
    ModelRenderer EnginePanel;
    ModelRenderer FuselageBottom;
    ModelRenderer TailBottom;
    ModelRenderer TailBack;
    ModelRenderer FuselageCover;
    ModelRenderer RudderTri1;
    ModelRenderer RudderTri2;
    ModelRenderer TailTri1;
    ModelRenderer TailTri2;
    ModelRenderer TailTri3;
    ModelRenderer TailTri4;
    ModelRenderer TailTri5;
    ModelRenderer TailTri6;
    ModelRenderer ElevatorLeft;
    ModelRenderer ElevatorLeftAlt;
    ModelRenderer ElevatorRight;
    ModelRenderer ElevatorRightAlt;
    ModelRenderer SupportStrut1;
    ModelRenderer SupportStrut2;
    ModelRenderer SupportStrut3;
    ModelRenderer SupportStrut4;
    ModelRenderer SupportStrut5;
    ModelRenderer SupportStrut6;
    ModelRenderer SupportStrut7;
    ModelRenderer SupportStrut8;
    ModelRenderer WheelSupport1;
    ModelRenderer Wheel1;
    ModelRenderer WheelSupport2;
    ModelRenderer Wheel2;
    ModelRenderer WheelSupport3;
    ModelRenderer Wheel3;
  
  public ModelBiplane()
  {
    textureWidth = 256;
    textureHeight = 256;
    
      WingTop = new ModelRenderer(this, 0, 0);
      WingTop.addBox(-64F, 0F, 0F, 128, 1, 24);
      WingTop.setRotationPoint(0F, -16F, 0F);
      WingTop.setTextureSize(256, 256);
      WingTop.mirror = true;
      setRotation(WingTop, 0F, 0F, 0F);
      WingBottom = new ModelRenderer(this, 0, 0);
      WingBottom.addBox(-64F, -0.1F, 0F, 128, 1, 24);
      WingBottom.setRotationPoint(0F, 0F, 0F);
      WingBottom.setTextureSize(256, 256);
      WingBottom.mirror = true;
      setRotation(WingBottom, 0F, 0F, 0F);
      FuselageLeft = new ModelRenderer(this, 0, 0);
      FuselageLeft.addBox(0F, -7F, -18F, 1, 8, 48);
      FuselageLeft.setRotationPoint(-8F, 0F, 0F);
      FuselageLeft.setTextureSize(256, 256);
      FuselageLeft.mirror = true;
      setRotation(FuselageLeft, 0F, 0F, 0F);
      FuselageRight = new ModelRenderer(this, 0, 0);
      FuselageRight.addBox(0F, 0F, -18F, 1, 8, 48);
      FuselageRight.setRotationPoint(7F, -7F, 0F);
      FuselageRight.setTextureSize(256, 256);
      FuselageRight.mirror = true;
      setRotation(FuselageRight, 0F, 0F, 0F);
      EnginePanel = new ModelRenderer(this, 0, 0);
      EnginePanel.addBox(-7F, 0F, 0F, 14, 8, 1);
      EnginePanel.setRotationPoint(0F, -7F, 29F);
      EnginePanel.setTextureSize(256, 256);
      EnginePanel.mirror = true;
      setRotation(EnginePanel, 0F, 0F, 0F);
      FuselageBottom = new ModelRenderer(this, 0, 0);
      FuselageBottom.addBox(-8F, 0F, 0F, 16, 1, 47);
      FuselageBottom.setRotationPoint(0F, 0F, -18F);
      FuselageBottom.setTextureSize(256, 256);
      FuselageBottom.mirror = true;
      setRotation(FuselageBottom, 0F, 0F, 0F);
      TailBottom = new ModelRenderer(this, 0, 0);
      TailBottom.addBox(-8F, 0F, -22F, 16, 1, 22);
      TailBottom.setRotationPoint(0F, 0F, -18F);
      TailBottom.setTextureSize(256, 256);
      TailBottom.mirror = true;
      setRotation(TailBottom, -0.106682F, 0F, 0F);
      TailBack = new ModelRenderer(this, 0, 0);
      TailBack.addBox(-7F, -3F, 0F, 14, 5, 1);
      TailBack.setRotationPoint(0F, -4F, -40F);
      TailBack.setTextureSize(256, 256);
      TailBack.mirror = true;
      setRotation(TailBack, 0F, 0F, 0F);
      FuselageCover = new ModelRenderer(this, 0, 0);
      FuselageCover.addBox(-8F, -2F, -16F, 14, 1, 42);
      FuselageCover.setRotationPoint(1F, -5F, -23F);
      FuselageCover.setTextureSize(256, 256);
      FuselageCover.mirror = true;
      setRotation(FuselageCover, 0F, 0F, 0F);
      RudderTri1 = new ModelRenderer(this, 0, 0);
      RudderTri1.addBox(0.01F, -2F, 0.1F, 1, 7, 11);
      RudderTri1.setRotationPoint(0F, -14F, -33F);
      RudderTri1.setTextureSize(256, 256);
      RudderTri1.mirror = true;
      setRotation(RudderTri1, -0.8922867F, 0F, 0F);
      RudderTri2 = new ModelRenderer(this, 0, 0);
      RudderTri2.addBox(0F, -2.5F, 0F, 1, 9, 6);
      RudderTri2.setRotationPoint(0F, -12.8F, -37.5F);
      RudderTri2.setTextureSize(256, 256);
      RudderTri2.mirror = true;
      setRotation(RudderTri2, 0F, 0F, 0F);
      TailTri1 = new ModelRenderer(this, 0, 0);
      TailTri1.addBox(0F, 0F, 0F, 1, 7, 9);
      TailTri1.setRotationPoint(-8F, -7F, -27F);
      TailTri1.setTextureSize(256, 256);
      TailTri1.mirror = true;
      setRotation(TailTri1, 0F, 0F, 0F);
      TailTri2 = new ModelRenderer(this, 0, 0);
      TailTri2.addBox(0F, 0F, -2F, 1, 6, 9);
      TailTri2.setRotationPoint(-8F, -7F, -34F);
      TailTri2.setTextureSize(256, 256);
      TailTri2.mirror = true;
      setRotation(TailTri2, 0F, 0F, 0F);
      TailTri3 = new ModelRenderer(this, 0, 0);
      TailTri3.addBox(0F, 0F, 0F, 1, 5, 4);
      TailTri3.setRotationPoint(-8F, -7F, -40F);
      TailTri3.setTextureSize(256, 256);
      TailTri3.mirror = true;
      setRotation(TailTri3, 0F, 0F, 0F);
      TailTri4 = new ModelRenderer(this, 0, 0);
      TailTri4.addBox(0F, 0F, 0F, 1, 7, 9);
      TailTri4.setRotationPoint(7F, -7F, -27F);
      TailTri4.setTextureSize(256, 256);
      TailTri4.mirror = true;
      setRotation(TailTri4, 0F, 0F, 0F);
      TailTri5 = new ModelRenderer(this, 0, 0);
      TailTri5.addBox(0F, 0F, -2F, 1, 6, 9);
      TailTri5.setRotationPoint(7F, -7F, -34F);
      TailTri5.setTextureSize(256, 256);
      TailTri5.mirror = true;
      setRotation(TailTri5, 0F, 0F, 0F);
      TailTri6 = new ModelRenderer(this, 0, 0);
      TailTri6.addBox(0F, 0F, 0F, 1, 5, 4);
      TailTri6.setRotationPoint(7F, -7F, -40F);
      TailTri6.setTextureSize(256, 256);
      TailTri6.mirror = true;
      setRotation(TailTri6, 0F, 0F, 0F);
      ElevatorLeft = new ModelRenderer(this, 0, 0);
      ElevatorLeft.addBox(-20F, 0.05F, 0F, 20, 1, 8);
      ElevatorLeft.setRotationPoint(-2F, -4F, -26F);
      ElevatorLeft.setTextureSize(256, 256);
      ElevatorLeft.mirror = true;
      setRotation(ElevatorLeft, 0F, -0.4164007F, 0F);
      ElevatorLeftAlt = new ModelRenderer(this, 0, 0);
      ElevatorLeftAlt.addBox(-19.5F, 0F, 0F, 20, 1, 8);
      ElevatorLeftAlt.setRotationPoint(-4F, -4F, -34.7F);
      ElevatorLeftAlt.setTextureSize(256, 256);
      ElevatorLeftAlt.mirror = true;
      setRotation(ElevatorLeftAlt, 0F, 0F, 0F);
      ElevatorRight = new ModelRenderer(this, 0, 0);
      ElevatorRight.addBox(-20F, 0.1F, -8F, 20, 1, 8);
      ElevatorRight.setRotationPoint(2F, -4F, -26F);
      ElevatorRight.setTextureSize(256, 256);
      ElevatorRight.mirror = true;
      setRotation(ElevatorRight, 0F, -2.725192F, 0F);
      ElevatorRightAlt = new ModelRenderer(this, 0, 0);
      ElevatorRightAlt.addBox(-0.5F, 0F, 0F, 20, 1, 8);
      ElevatorRightAlt.setRotationPoint(4F, -4F, -35.1F);
      ElevatorRightAlt.setTextureSize(256, 256);
      ElevatorRightAlt.mirror = true;
      setRotation(ElevatorRightAlt, 0F, 0F, 0F);
      SupportStrut1 = new ModelRenderer(this, 0, 0);
      SupportStrut1.addBox(0F, -14F, 0F, 1, 15, 1);
      SupportStrut1.setRotationPoint(-41F, -1F, 4F);
      SupportStrut1.setTextureSize(256, 256);
      SupportStrut1.mirror = true;
      setRotation(SupportStrut1, 0F, 0F, 0F);
      SupportStrut2 = new ModelRenderer(this, 0, 0);
      SupportStrut2.addBox(0F, -14F, 0F, 1, 15, 1);
      SupportStrut2.setRotationPoint(-41F, -1F, 19F);
      SupportStrut2.setTextureSize(256, 256);
      SupportStrut2.mirror = true;
      setRotation(SupportStrut2, 0F, 0F, 0F);
      SupportStrut3 = new ModelRenderer(this, -1, -1);
      SupportStrut3.addBox(0F, -14F, 0F, 1, 15, 1);
      SupportStrut3.setRotationPoint(41F, -1F, 4F);
      SupportStrut3.setTextureSize(256, 256);
      SupportStrut3.mirror = true;
      setRotation(SupportStrut3, 0F, 0F, 0F);
      SupportStrut4 = new ModelRenderer(this, -1, -1);
      SupportStrut4.addBox(0F, -14F, 0F, 1, 15, 1);
      SupportStrut4.setRotationPoint(41F, -1F, 19F);
      SupportStrut4.setTextureSize(256, 256);
      SupportStrut4.mirror = true;
      setRotation(SupportStrut4, 0F, 0F, 0F);
      SupportStrut5 = new ModelRenderer(this, 0, 0);
      SupportStrut5.addBox(0F, 0F, 0F, 1, 8, 1);
      SupportStrut5.setRotationPoint(7F, -15F, 8F);
      SupportStrut5.setTextureSize(256, 256);
      SupportStrut5.mirror = true;
      setRotation(SupportStrut5, 0F, 0F, 0F);
      SupportStrut6 = new ModelRenderer(this, 0, 0);
      SupportStrut6.addBox(0F, 0F, 0F, 1, 8, 1);
      SupportStrut6.setRotationPoint(7F, -15F, 18F);
      SupportStrut6.setTextureSize(256, 256);
      SupportStrut6.mirror = true;
      setRotation(SupportStrut6, 0F, 0F, 0F);
      SupportStrut7 = new ModelRenderer(this, 0, 0);
      SupportStrut7.addBox(0F, 0F, 0F, 1, 8, 1);
      SupportStrut7.setRotationPoint(-8F, -15F, 8F);
      SupportStrut7.setTextureSize(256, 256);
      SupportStrut7.mirror = true;
      setRotation(SupportStrut7, 0F, 0F, 0F);
      SupportStrut8 = new ModelRenderer(this, 0, 0);
      SupportStrut8.addBox(0F, 0F, 0F, 1, 8, 1);
      SupportStrut8.setRotationPoint(-8F, -15F, 18F);
      SupportStrut8.setTextureSize(256, 256);
      SupportStrut8.mirror = true;
      setRotation(SupportStrut8, 0F, 0F, 0F);
      WheelSupport1 = new ModelRenderer(this, 0, 0);
      WheelSupport1.addBox(0F, 0F, 0F, 1, 5, 1);
      WheelSupport1.setRotationPoint(-5F, 1F, 18F);
      WheelSupport1.setTextureSize(256, 256);
      WheelSupport1.mirror = true;
      setRotation(WheelSupport1, 0F, 0F, 0F);
      Wheel1 = new ModelRenderer(this, 0, 0);
      Wheel1.addBox(0F, 0F, 0F, 1, 3, 3);
      Wheel1.setRotationPoint(-5F, 6F, 17F);
      Wheel1.setTextureSize(256, 256);
      Wheel1.mirror = true;
      setRotation(Wheel1, 0F, 0F, 0F);
      WheelSupport2 = new ModelRenderer(this, 0, 0);
      WheelSupport2.addBox(0F, 0F, 0F, 1, 5, 1);
      WheelSupport2.setRotationPoint(4F, 1F, 18F);
      WheelSupport2.setTextureSize(256, 256);
      WheelSupport2.mirror = true;
      setRotation(WheelSupport2, 0F, 0F, 0F);
      Wheel2 = new ModelRenderer(this, 0, 0);
      Wheel2.addBox(0F, 0F, 0F, 1, 3, 3);
      Wheel2.setRotationPoint(4F, 6F, 17F);
      Wheel2.setTextureSize(256, 256);
      Wheel2.mirror = true;
      setRotation(Wheel2, 0F, 0F, 0F);
      WheelSupport3 = new ModelRenderer(this, 0, 0);
      WheelSupport3.addBox(0F, 0F, 0F, 1, 2, 1);
      WheelSupport3.setRotationPoint(0F, 0F, -28F);
      WheelSupport3.setTextureSize(256, 256);
      WheelSupport3.mirror = true;
      setRotation(WheelSupport3, 0F, 0F, 0F);
      Wheel3 = new ModelRenderer(this, 0, 0);
      Wheel3.addBox(0F, 0F, 0F, 1, 3, 3);
      Wheel3.setRotationPoint(0F, 2F, -29F);
      Wheel3.setTextureSize(256, 256);
      Wheel3.mirror = true;
      setRotation(Wheel3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    WingTop.render(f5);
    WingBottom.render(f5);
    FuselageLeft.render(f5);
    FuselageRight.render(f5);
    EnginePanel.render(f5);
    FuselageBottom.render(f5);
    TailBottom.render(f5);
    TailBack.render(f5);
    FuselageCover.render(f5);
    RudderTri1.render(f5);
    RudderTri2.render(f5);
    TailTri1.render(f5);
    TailTri2.render(f5);
    TailTri3.render(f5);
    TailTri4.render(f5);
    TailTri5.render(f5);
    TailTri6.render(f5);
    ElevatorLeft.render(f5);
    ElevatorLeftAlt.render(f5);
    ElevatorRight.render(f5);
    ElevatorRightAlt.render(f5);
    SupportStrut1.render(f5);
    SupportStrut2.render(f5);
    SupportStrut3.render(f5);
    SupportStrut4.render(f5);
    SupportStrut5.render(f5);
    SupportStrut6.render(f5);
    SupportStrut7.render(f5);
    SupportStrut8.render(f5);
    WheelSupport1.render(f5);
    Wheel1.render(f5);
    WheelSupport2.render(f5);
    Wheel2.render(f5);
    WheelSupport3.render(f5);
    Wheel3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
